### ISSUE TITLE
Seems a undefined variable in django_auth_kerberos/backends.py

### ISSUE THREAD

**Issue by qq915522927** [02strich/django-auth-kerberos#14]
![image](https://user-images.githubusercontent.com/29817206/45675458-fe736f80-bb61-11e8-8aba-969ce03770e3.png)

**Comment by 02strich** [comment]
Fixed in 416c2e2fafe6f0dbddf79bef6f6dbb90b04ceedc. Thanks for raising it.

Do you need this to be released it PIP?
